### ISSUE TITLE
default value unexpected behaviour

### ISSUE THREAD

**Issue by gismoranas** [trueaccord/ScalaPB#100]
I have this protobuf code

`
message Foo {
  optional int32 schema = 1 [default = 11];
}
`

If I run this

```
val foo = new Foo(None)
println(foo.parseFrom(foo.toByteArray).getSchema) // 11
println(foo.parseFrom(foo.toByteArray).schema) // None
```

I suppose you set 11 in the getter instead of setting Some(11) in schema directly. Isn't this an inconsistent state?

**Comment by thesamet** [comment]
This distinction between set and unset fields comes from the proto2 spec. A field may be either present or not in a message, which is modeled in ScalaPB as (`Some(_)` or `None`). Only when you call `getX` the default value is provided.

This is modeled after the official Java implementation, see "Singular value fields" at https://developers.google.com/protocol-buffers/docs/reference/java-generated#fields
which they have for each field X two methods: `hasX()` and `getX()`. We basically combine these two to a single optional field.

**Comment by gismoranas** [comment]
So in Java the state of my object would be:

``` 
foo.hasSchema() // false because in scala you return None
foo.getSchema() // 11
```

does this make sense?

**Comment by thesamet** [comment]
Exactly. We're just mapping these two fields to a single `Option`. You may be interested in trying proto3, where primitives are not wrapped in Options, but there are no default values either (default is 0 for numerics, empty string, etc)
