### ISSUE TITLE
Won't decode not packed `repeated` if declared as `packed` in `.proto` and vice-versa

### ISSUE THREAD

**Issue by gpoulin** [trueaccord/ScalaPB#102]
Protobuf specification requires decoder to expect both packed and not packed sequence regardless of the declaration in the `.proto` [ref](https://developers.google.com/protocol-buffers/docs/encoding#packed). Currently, ScalaPB decoder expects only the form declared in the `.proto`.

```proto
message ProtoPacked {
    repeated int32 a = 1 [packed=true];
}

message ProtoUnpacked {
    repeated int32 a = 1;
}
```

```scala
// Simple example that are currently failing
val a = Seq(1)
ProtoUnpacked.parseFrom(ProtoPacked(a).toByteArray).a must_== a
ProtoPacked.parseFrom(ProtoUnpacked(a).toByteArray).a must_== a

// extreme example that should also work
val extremeCase = ProtoPacked(Seq(0, 1)).toByteArray ++
  ProtoUnpacked(Seq(2, 3, 4)).toByteArray ++
  ProtoPacked(Seq(5, 6, 7)).toByteArray ++
  ProtoUnpacked(Seq(8)).toByteArray
  
val expected = (0 until 9).toSeq
ProtoUnpacked.parseFrom(extremeCase).a must_== expected
ProtoPacked.parseFrom(extremeCase).a must_== expected
```

**Comment by thesamet** [comment]
Thanks for reporting. Acknowledged - current implementation of ScalaPB does not handle this properly. Will fix soon.

**Comment by thesamet** [comment]
Thanks for reporting. Acknowledged - current implementation of ScalaPB does not handle this properly. Will fix soon.

**Comment by thesamet** [comment]
Thanks for reporting. Confirmed - current implementation of ScalaPB does not handle this properly. Will fix soon.
