### ISSUE TITLE
Option for companion objects to extend specified classes/traits

### ISSUE THREAD

**Issue by ngthanhtrung** [trueaccord/ScalaPB#105]
I know currently we have the option to extend generated classes with custom super classes/traits:

```protobuf
message MyMessage {
  option (scalapb.message).extends = "MySuperClass";
  int32 dummy = 999;
}
```

However, I often find myself wanting to extend generated companion objects with custom super classes/traits, maybe something like that will help:

```protobuf
message MyMessage {
  option (scalapb.message).extends = "MySuperClass";
  option (scalapb.message).companion_extends = "MySuperCompanionClass";
  int32 dummy = 999;
}
```

Please let me know if this would align with your roadmap. I'm happy to submit a PR. Thanks.

**Comment by thesamet** [comment]
Yes, PR for this will be welcome.
