### ISSUE TITLE
Make grpc service name visible in generated code

### ISSUE THREAD

**Issue by eiennohito** [trueaccord/ScalaPB#108]
Right now it is inlined, but exposing it will make it easier for more advanced code.

For example, I am trying to use grpc with akka streams for backpressure support.

I can submit a pull request containing base trait for services and patch for generator.

`trait GrpcService { def name: String }`

**Comment by thesamet** [comment]
Fixed by a754b35a226fba283acf35a5245de8617272aec6.

The service name can be exposed through Service.descriptor.getName()
