### ISSUE TITLE
JSON Marshalling / Unmarshalling Support for generated Case Classes

### ISSUE THREAD

**Issue by nattyddubbs** [trueaccord/ScalaPB#110]
Proto 3 will support JSON serialization as outlined [here](https://developers.google.com/protocol-buffers/docs/proto3#json). 

There is already a [Java implementation](https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java) that will marshall generated Java classes.

It would be just great if ScalaPB supported this functionality as well. I know that I can create the Java classes and use those but build in functionality to support marshall / umarshall from case class to JSON would be a huge selling point for using ScalaPB.

**Comment by thesamet** [comment]
Done! See https://trueaccord.github.io/ScalaPB/json.html

**Comment by nattyddubbs** [comment]
Does the implementation match the specification in that "If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space." ([protobuf spec](https://developers.google.com/protocol-buffers/docs/proto3#json)). It looks like it could optionally contain the default values as well however it would be good if for consistency with the library it omitted those.

Thank you for the quick turnaround on this! I am really enjoying using your product.

**Comment by terro** [comment]
It seems that in current version (0.5.45), the default value is omitted. Is there any way to contain it in the JSON?

**Comment by thesamet** [comment]
Yes, we're tracking this in #183. The code is already in, release will come in the next few days.

**Comment by terro** [comment]
That's great! Thanks!
