### ISSUE TITLE
grpc should not depend on grpc-all

### ISSUE THREAD

**Issue by eiennohito** [trueaccord/ScalaPB#113]
1) It will be removed: https://github.com/grpc/grpc-java/issues/1597
2) It repackages classes for everything making navigation to sources in IDE a pain.

Proposal for fix: runtime should depend on grpc-stub, tests should depend on grpc-netty.

**Comment by eiennohito** [comment]
1) Edit: My bad, it will become a simple aggregation project. 

However, I believe that dependency on all is still not needed.
Service generation depends only on `grpc-stub` and should not expose more dependencies.

**Comment by thesamet** [comment]
Fine by me, PR will be welcome.
