### ISSUE TITLE
ScalaPB + Intellij

### ISSUE THREAD

**Issue by nykolaslima** [trueaccord/ScalaPB#120]
The default ScalaPB configuration only generated the `.class` into the output dir.

I need to have the generated `.scala` classes in order to Intellij see it. How can I configure the `.scala` classes output dir?

**Comment by nadavsr** [comment]
Hi Nykolas,

IntelliJ should be able to see the files in the default place where ScalaPB
puts them, however you can control this by putting something like the
following in build.sbt:

scalaSource in PB.protobufConfig <<= (sourceManaged in Compile) { _ / "
compiled_protobuf" }

or

scalaSource in PB.protobufConfig := file("path/to/somewhere")

**Comment by nykolaslima** [comment]
@nadavsr thank you very much! I was already posting the solution because I saw it on another issue, thank you anyway!

```
scalaSource in PB.protobufConfig <<= (sourceDirectory in Compile)(_ / "generated-proto")
```

**Comment by doctapp** [comment]
Had the same problem, IntelliJ won't see the generated proto classes. Used the following trick:

> scalaSource in PB.protobufConfig <<= (sourceDirectory in Compile)(_ / "generated-proto")

@nadavsr You mentioned IntelliJ should see the generated classes, why do we need to add this? I'm using IntelliJ 2016.1.2 with ScalaPB 0.5.27.

Thanks

**Comment by thesamet** [comment]
IntelliJ should see the files in the right place even if you don't add
this. The limitation is that IntelliJ won't generate the files. You need to
generate the files from the SBT shell (by compiling there first). IntelliJ
should pick them up.

On Tue, May 31, 2016 at 11:54 AM, Martin Tapp <notifications@github.com>
wrote:

> Had the same problem, IntelliJ won't see the generated proto classes. Used
> the following trick:
>
> scalaSource in PB.protobufConfig <<= (sourceDirectory in Compile)(_ /
> "generated-proto")
>
> @nadavsr <https://github.com/nadavsr> You mentioned IntelliJ should see
> the generated classes, why do we need to add this? I'm using IntelliJ
> 2016.1.2 with ScalaPB 0.5.27.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/120#issuecomment-222785123>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASwrbjw3n-QEvKN9aJ8jagXzcABj27lks5qHIPegaJpZM4IhxLm>
> .
>



-- 
-Nadav

**Comment by doctapp** [comment]
By default, my setup doesn't work with IntelliJ. I see the files generated
under target/scala-2.10/src_managed/[package]/[* proto classes].scala. I
did a full clean/compile with sbt. Even tried a SBT refresh from IntelliJ.
Only way IntelliJ sees the generated classes after being compiled from sbt
is if I add `scalaSource in PB.protobufConfig <<= (sourceDirectory in
Compile)(_ / "generated-proto")`.

What can I check?

Thanks

**Comment by nadavsr** [comment]
Can you try to 'rm -rf .idea' and reimport the project into IntelliJ?

**Comment by doctapp** [comment]
Thanks, but that didn't work. Seems anything under target/ is not
considered sources by IntelliJ. I have the same problem with Scrooge for
Thrift and did the same hack of redirecting to a generated folder under
src/main.

If you know of a better trick or that would embed this within ScalaPB, that
would be super!

Martin

**Comment by githubsheng** [comment]
`scalaSource in PB.protobufConfig <<= (sourceDirectory in Compile)(_ / "generated-proto")`
does not seem to work with the latest scalapb. I got `value protobufConfig is not a member of object sbtprotoc.ProtocPlugin.autoImport.PB` error. Using the latest scalapb the generated files are inside `target` folder and Intellij's default setting ignores anything in that folder.

**Comment by rafaparadela** [comment]
@githubsheng 

```scala
import sbtprotoc.ProtocPlugin.ProtobufConfig
```

And then

```scala
scalaSource in ProtobufConfig <<= (sourceDirectory in Compile)(_ / "generated-proto")
```

**Comment by ovesco** [comment]
For those having an error with SBT compilation, this line did the job for me (based on @rafaparadela's answer, but with the new syntax)
```scala
scalaSource in sbtprotoc.ProtocPlugin.ProtobufConfig := sourceDirectory.value / "generated-proto"
```
