### ISSUE TITLE
proto3 & grpc

### ISSUE THREAD

**Issue by ahjohannessen** [trueaccord/ScalaPB#127]
As I understand it everything is suddenly an optional field in proto3, perhaps for reasons that are understandable considering languages such as Java and C#. 

However, if messages are used to communicate via gRPC in a Scala setting then it becomes very cumbersome to ensure required fields on messages, because suddenly you also need to pattern match wrt. `Option` even when you *know* that field is required.

Would it make sense to build in required as some sort of extension to ScalaPB when using `proto3` that causes the code generator to generate non-optional fields on case classes? I can see that falls a bit apart when used in a mixed setting.

Secondly, if the above is a bad idea, would it work if one defines messages that need that sort of semantics in a proto file that uses syntax v2 and then defines gRPC in a different proto that uses syntax v3 and imports the one with syntax v2?

**Comment by eiennohito** [comment]
1) It is completely possible to mix v2 and v3 style files. I do it personally. [Protobuf spec supports it](https://developers.google.com/protocol-buffers/docs/proto3#using-proto2-message-types), so it is a bug if something does not work. map<> does not work with v2 syntax though.

2) With v3 only messages are wrapped with option. Primitive fields stay as they are.

**Comment by ahjohannessen** [comment]
@eiennohito Uh, that is nice :) I can see this from the docs:

>However, proto2 enums cannot be used in proto3 syntax.

What is the deal with that. Seems to compile when I import a proto2 message type that uses enum into a proto3 file with a grpc service?

**Comment by thesamet** [comment]
@ahjohannessen would the solution suggested at #40 would work for you? That is, add field-level option that tells the generator not to wrap a value in an option. Something like:

    option Message msg = 1 [(scalapb).no_box = 1]

This would apply to any field in proto2, and for proto3 this is relevant only to messages since primitives are not boxed.

**Comment by ahjohannessen** [comment]
@thesamet In a pure scala environment I suppose that would be fine - however it is not so much an issue as I can define messages in proto2 and use those with services generated in proto3.

However, what I think is more interesting to investigate is the generated service code with respect to being able to use a scalaz Task instead of a scala Future plus making the code more Scala / FP like.

**Comment by ahjohannessen** [comment]
Furthermore, being able between scalaz-stream `Process` (soon fs2 `Stream`) and `StreamObserver` would be awesome :)

**Comment by thesamet** [comment]
Perhaps the scalaz-stream suggestion should go into its own separate github issue, with more details? It seems like the discussion here is diverging to two paths (scalaz, and option boxing), so if there's interest in #40 let's continue there?

**Comment by ahjohannessen** [comment]
Yep, agree 👍
