### ISSUE TITLE
Referring to non-existant method ...

### ISSUE THREAD

**Issue by thompson4822** [trueaccord/ScalaPB#129]
When I use my ScalaPB compiled protobuf code in Scala.js, I'm getting the following:

Referring to non-existent method java.lang.Float$.floatToRawIntBits(scala.Float)scala.Int

I saw that there was some discussion of this with the author of Scala.js. Is there a newer version of ScalaPB in which this is resolved (I'm using 0.5.29 atm)?

Thanks,

Steve

**Comment by xuwei-k** [comment]
https://github.com/trueaccord/ScalaPB/issues/99

**Comment by thesamet** [comment]
Duplicate. Closing (will be fixed in next release)
