### ISSUE TITLE
plugin version 0.4.20 doesn't actually exist

### ISSUE THREAD

**Issue by IoDmitri** [trueaccord/ScalaPB#130]
Within the examples the following line, `addSbtPlugin("com.trueaccord.scalapb" % "sbt-scalapb" % "0.4.20")`, doesn't download the plugin, but changing the version to 0.5.29 does work.

**Comment by thesamet** [comment]
Can you provide the error you are getting when using 0.4.20. The binaries
for it do exist:
http://central.maven.org/maven2/com/trueaccord/scalapb/sbt-scalapb_2.10_0.13/0.4.20/

On Wed, Jun 15, 2016 at 11:12 AM, Dmitri Iourovitski <
notifications@github.com> wrote:

> Within the examples the following line, addSbtPlugin("com.trueaccord.scalapb"
> % "sbt-scalapb" % "0.4.20"), doesn't download the plugin, but changing
> the version to 0.5.29 does work.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/130>, or mute the thread
> <https://github.com/notifications/unsubscribe/AASwrVXYx_ndIi4dYhjWZc7Hr2iBS1cnks5qMECqgaJpZM4I2o-n>
> .
>



-- 
-Nadav

**Comment by IoDmitri** [comment]
Using the configuration above, I was unable to actually download the plugin until I changed it to version 0.5.29.

**Comment by thesamet** [comment]
Great that 0.5.29 works for you. For 0.4.20: can you provide instructions on how to reproduce the problem you are seeing so we can investigate?  If I follow the instructions http://trueaccord.github.io/ScalaPB/sbt-settings.html, things work fine.

**Comment by IoDmitri** [comment]
I have an [SO](http://stackoverflow.com/questions/37842081/scalapb-not-recognized-within-build-sbt) question pertaining to this issue, I lay out the steps I took to try and install it. I simply copy-pasted the instructions and they didn't work for me.

**Comment by thesamet** [comment]
Resolved by upgrading SBT to 0.13.11.
