### ISSUE TITLE
Message containing a Map not properly compiled

### ISSUE THREAD

**Issue by BenFradet** [trueaccord/ScalaPB#133]
I'm using 0.5.31, but afaict this problem is also currently in `master`.

I have a simple message:

```protobuf
message MyMessage {
  map<string, string> map = 1;
}
```

The problem is that a case class is generated for an entry in the map like so:

```scala
case class MapEntry(key: scala.Option[String] = None, value: scala.Option[String] = None)
```

and the following `keyValueMapper` is generated:

```scala
implicit val keyValueMapper: TypeMapper[MyMessage.MapEntry, (String, String)] =
  TypeMapper[MyMessage.MapEntry, (String, String)](
     __m => (__m.key, __m.getValue))(
     __p => MyMessage.MapEntry(__p._1, Some(__p._2)))
```

Unfortunately, this doesn't compile.

The problems are:
  - the first function has to be of type `MapEntry => (String, String)`  and is actually of type `MapEntry => (Option[String], String)`
  - the second function has to be of type `(String, String) => MapEntry`. However `MapEntry` takes two options as parameters `__p._1` is a `String`

I guess there are two solutions:
  - `case class MapEntry(key: String = "", value: scala.Option[String] = None)`
  - or `__m => (__m.getKey, __m.getValue)` and `__p => MapEntry(Some(__p._1), Some(__p._2))`

**Comment by BenFradet** [comment]
I'd be glad to work on a PR for either solution.

**Comment by thesamet** [comment]
Thanks, looks like `map<>` was never working for proto2 syntax (only for proto3). Commit ec3852e adds tests for maps under proto2.

**Comment by BenFradet** [comment]
Thanks a lot, is there any release planned containing this?

**Comment by thesamet** [comment]
I'll release 0.5.32 this weekend.

**Comment by BenFradet** [comment]
Great, thanks!
