### ISSUE TITLE
function are duplicated when name contains underscores.

### ISSUE THREAD

**Issue by crakjie** [trueaccord/ScalaPB#144]
When there is IAB21_1 and IAB2_11 ScalaPB generate function without underscore that make problem 

``` method isIab211 is defined twice ```

The proto exemple can be found [here](https://github.com/BeeswaxIO/beeswax-api/blob/master/beeswax/openrtb/openrtb_common.proto)

**Comment by thesamet** [comment]
Are you on a recent 0.5.x release? This seems like a duplicate of #94

**Comment by crakjie** [comment]
I'm using ```addSbtPlugin("com.trueaccord.scalapb" % "sbt-scalapb" % "0.4.20")```as seen in README.md

**Comment by crakjie** [comment]
I have follow the information found in the exemple project tu set the build.sbt and the scalapb.sbt of the 0.5.29 tag
And indeed the bug was already fixed !
Thanks
