### ISSUE TITLE
Provide a typeclass for retrieving the ServiceCompanion of a service. 

### ISSUE THREAD

**Issue by Baccata** [trueaccord/ScalaPB#154]
Hi, in the same way that we can implicitly get a `GeneratedMessageCompanion` in order to get the descriptor of a message type (among other things), it'd be great if we could access the `ServiceCompanion` directly from the service's type, in order to perform some runtime introspection for generic programming purposes. 

Thank you for this product, it's really convenient to use 👍

**Comment by felixt-cake** [comment]
👍

**Comment by thesamet** [comment]
There was some complication around this change, where the outer class (SomeServiceGrpc) can't extend `ServiceCompanion[A]` for some type `A` which is defined inside it. To solve it, the companion object is now a companion object to the actual service trait.

See usage example here: 
https://github.com/trueaccord/ScalaPB/blob/master/e2e/src/test/scala/GrpcServiceScalaServerSpec.scala#L15

In addition, services now have `serviceCompanion` method that references this new companion object.
