### ISSUE TITLE
Add fromName to GeneratedEnumCompanion

### ISSUE THREAD

**Issue by kbalyasnikov** [trueaccord/ScalaPB#160]
GeneratedEnumCompanion have fromValue method, but sometimes it's required to get Enum value by it's name. I'm proposing addition of fromName and fromNameCaseInsensitive methods.

**Comment by thesamet** [comment]
If `E` is a `GeneratedEnumCompanion`, then you have `E.values.find(_.name == "SomeName")` (similarly for case insensitive comparison)

**Comment by kbalyasnikov** [comment]
Actually for now i'm using exactly same code to get enum value by name, but that's not convenient in any way. It's a common for enumeration to have both byId and byName access methods, for example take a look at [scala.Enumeration#withName](http://www.scala-lang.org/api/2.11.8/#scala.Enumeration), [enumeratum](https://github.com/lloydmeta/enumeratum) or [Java Enum#valueOf](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html).

**Comment by thesamet** [comment]
Yeah, I can see the use for a handy `fromName` method - reopening for it. I think that `fromNameCaseInsensitive` is too specific though - if it's needed in your project you can add this helper through implicit conversion.

**Comment by kbalyasnikov** [comment]
Thanks!
