### ISSUE TITLE
Constructor on a proto2 required field is generated with a default value

### ISSUE THREAD

**Issue by shshe** [trueaccord/ScalaPB#165]
Hey there, I first want to say thanks for a great project!

I'm running into a problem where the following proto2 file:
```
syntax = "proto2";

package test;

message TestMessage {
  required string testField = 1;
}
```

Is generating a constructor with default values:
```
final case class TestMessage(
    testField: String = ""
    ....
```

Here's my build.sbt:
```
import com.trueaccord.scalapb.{ScalaPbPlugin => PB}

name := "scalapb-test"
scalaVersion := "2.11.8"

PB.protobufSettings
PB.scalapbVersion := "0.5.38"
PB.runProtoc in PB.protobufConfig := (args =>
  com.github.os72.protocjar.Protoc.runProtoc("-v300" +: args.toArray))
version in PB.protobufConfig := "3.0.0"

libraryDependencies ++= Seq(
  "com.google.protobuf" % "protobuf-java" % "3.0.0" % PB.protobufConfig,
  "io.grpc" % "grpc-netty" % "1.0.0",
  "com.trueaccord.scalapb" %% "scalapb-runtime-grpc" % (PB.scalapbVersion in PB.protobufConfig).value,
  "com.trueaccord.scalapb" %% "scalapb-runtime" % PB.scalapbVersion.value % PB.protobufConfig
)
```

I've dug around the codebase a bit and it seems like the protobuf file is being detected as proto3 by scalapb instead of proto2. Any ideas on what's wrong?

**Comment by ahjohannessen** [comment]
@thesamet Is this intended behavior?

**Comment by thesamet** [comment]
Yes, this is the current intended behavior. @shshe - any concerns with the current behavior?

**Comment by shshe** [comment]
@thesamet The [documentation](http://trueaccord.github.io/ScalaPB/generated-code.html) states that required fields have no default values in the generated constructor - I was hoping we could keep this behavior. 

We're migrating from Thrift to ScalaPB because of it's awesome Scala-specific support (e.g., adding traits), and this one issue is a blocker. Our Thrift schemas use required fields quite a bit and we want to ensure that clients that create a message purposefully specify the values for some fields as opposed to relying on defaults.

Any thoughts on supporting required constructor parameters again?

**Comment by thesamet** [comment]
You are right. Looks like the original intent of requiring the value was lost at some point. Let me see if there's any reason why we changed it. I don't mind reverting to the original documented way.

**Comment by shshe** [comment]
Thank you so much @thesamet!
