### ISSUE TITLE
Make it possible to run ScalaPB outside SBT

### ISSUE THREAD

**Issue by thesamet** [trueaccord/ScalaPB#17]

**Comment by ahjohannessen** [comment]
@thesamet Have you guys seen this: https://github.com/os72/protoc-jar ?

**Comment by nadavsr** [comment]
@ahjohannessen This looks really useful. Thanks!

**Comment by ahjohannessen** [comment]
@nadavsr Yep, that could eliminate the need to have a `install_protobuf.sh` for CI and utilize dependency caching.

**Comment by ahjohannessen** [comment]
@nadavsr @thesamet  Would it be possible that you guys upgrade to sbt-protobuf 0.4.0: https://github.com/sbt/sbt-protobuf/blob/master/notes/0.4.0.markdown

It has ability to run `protoc-jar` as issue https://github.com/sbt/sbt-protobuf/issues/23 is closed.

**Comment by thesamet** [comment]
Yes, this is planned to happen soon.

On Thu, May 7, 2015 at 4:16 AM, Alex Henning Johannessen <
notifications@github.com> wrote:

> @nadavsr <https://github.com/nadavsr> @thesamet
> <https://github.com/thesamet> Would it be possible that you guys upgrade
> to sbt-protobuf 0.4.0:
> https://github.com/sbt/sbt-protobuf/blob/master/notes/0.4.0.markdown
>
> It has ability to run protoc-jar as issue sbt/sbt-protobuf#23
> <https://github.com/sbt/sbt-protobuf/issues/23> is closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/17#issuecomment-99818456>.
>



-- 
-Nadav

**Comment by thesamet** [comment]
I've built ScalaPB 0.4.12 to depend on sbt-protobuf 0.4.0. I added to http://trueaccord.github.io/ScalaPB/sbt-settings.html instructions on how to use protoc-jar to avoid the dependency on protoc.

This is progress in the right direction, but the main issue of running ScalaPB outside SBT still remains.

**Comment by ahjohannessen** [comment]
This is great! :+1: Thank you very much for doing this :) Going to try it out now

**Comment by ahjohannessen** [comment]
It works great :+1: I wondered if the following is from your code or protoc-jar:
```
protoc-jar: protoc version: 261, detected platform: mac os x/x86_64
protoc-jar: executing: [/var/folders/y5/lswvltf14fx02nn9xhtv_65m0000gn/T/protoc4087409384165246742.exe, --plugin=protoc-gen-scala=...
```

It detects OS X correctly, but then it logs that it executes an `.exe`. That is a bit odd.

**Comment by ahjohannessen** [comment]
Found that it comes from here: https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L103

**Comment by thesamet** [comment]
There is now a supported way to run ScalaPB directly ftrom the command line, outside SBT. Look for `spbc` in http://trueaccord.github.io/ScalaPB/
