### ISSUE TITLE
Compilation issue with custom field extension

### ISSUE THREAD

**Issue by aemoncannon** [trueaccord/ScalaPB#172]
This might just be me doing things wrong, but here's what I'm hitting. My proto has a custom field extension like so...

```protobuf
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  bool req = 66666;
}

message User {
  double id = 1 [(req) = true];
}
```

And the generated code of top level ModelProto.java looks like...

```scala
  val req: com.trueaccord.scalapb.GeneratedExtension[com.google.protobuf.DescriptorProtos.FieldOptions, Boolean] =
    com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(66666, _.getVarintList)({__valueIn => __valueIn != 0})
```

This fails with:

```scala
ModelProto.scala:84: polymorphic expression cannot be instantiated to expected type;
[error]  found   : [J <: com.trueaccord.scalapb.GeneratedExtension.JavaExtendee[J]]com.trueaccord.scalapb.GeneratedExtension[J,Option[Boolean]]
[error]     (which expands to)  [J <: com.google.protobuf.Message with com.google.protobuf.GeneratedMessageV3.ExtendableMessage[J]]com.trueaccord.scalapb.GeneratedExtension[J,Option[Boolean]]
[error]  required: com.trueaccord.scalapb.GeneratedExtension[com.google.protobuf.DescriptorProtos.FieldOptions,Boolean]
[error]     com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(66666, _.getVarintList)({__valueIn => __valueIn != 0})
```

Could it be a problem that I'm including both the proto library and scala-js separately? Sbt doesn't complain of any version conflicts though...

  "com.google.protobuf" % "protobuf-java" % "3.0.2",
  "com.google.protobuf" % "protobuf-java-util" % "3.0.2",
  "com.trueaccord.scalapb" % "scalapb-runtime_2.11" % "0.5.41",

Thanks!

**Comment by aemoncannon** [comment]
Btw, my protos all have syntax = "proto3";

**Comment by thesamet** [comment]
Looks like the file where the options are defined must have proto2 syntax. The usages can be from either proto2 and proto3. I'll investigate.

**Comment by aemoncannon** [comment]
That was quick Thanks!
