### ISSUE TITLE
Can we include the scala.js jars in the release 

### ISSUE THREAD

**Issue by LogicalTime** [trueaccord/ScalaPB#173]
It would be useful for people to have the full set of jars and their dependencies including the scalaJs jars in the release zip. Would that be hard to do?

**Comment by thesamet** [comment]
Can you elaborate how this is going to be used? sbt, mvn and all build tools take care of downloading the dependencies (and the dependencies' dependencies').

**Comment by LogicalTime** [comment]
Some development environments do not have access to the net so dependency bundles are useful in those situations. Not a big deal though, just thought if it was easy to do it would be nice and perhaps make sense to have all released code in the release bundle.

**Comment by thesamet** [comment]
Will pass on this for now - it's probably better to solve dependency packaging at a different layer than from ScalaPB (for example, using the sbt assembly plugin on a machine that's connected to the internet).
