### ISSUE TITLE
proto3 fields of some type [A] are not wrapped in Option[A]

### ISSUE THREAD

**Issue by elmalto** [trueaccord/ScalaPB#190]
Running into the following issue

with 

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.1")

libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.5.43"
```

and using e.g.
```
syntax = "proto3";

message MyFoo {
    int32 fooValue = 1;
}
```

then I get
```
final case class MyFoo(fooValue: Long = 0L)
```

which I think should be of type ```Option[Long] = None```

**Comment by elmalto** [comment]
just saw this is feature, not a bug. will revert to old version then :)

**Comment by thesamet** [comment]
@elmalto For proto3, please consider using Primitive Wrappers, as described in https://trueaccord.github.io/ScalaPB/customizations.html to get `Option[A]`.
