### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by lkysow** [trueaccord/ScalaPB#20]
Hey Guys,

Thanks for the awesome lib. On this page http://trueaccord.github.io/ScalaPB/customizations.html you misspelled `libraryDependencies` (you're missing the `d`)

```
libraryDepenencies += "com.trueaccord.scalapb" %% "scalapb-runtime" % "0.4.9" % PB.protobufConfig
```

**Comment by thesamet** [comment]
Thanks for reporting. Fixed in e4d5dc.
