### ISSUE TITLE
doesn't respect the protoc setting of sbt-protobuf

### ISSUE THREAD

**Issue by AEtherSurfer** [trueaccord/ScalaPB#21]
See: protoc at https://github.com/sbt/sbt-protobuf#settings

Looks like  "protoc" is hardcoded here https://github.com/trueaccord/ScalaPB/blob/57695392abbca236e9121cc6fad624200e29b6f1/compiler-plugin/src/main/scala/com/trueaccord/scalapb/compiler/Process.scala#L142

**Comment by AEtherSurfer** [comment]
Also on line 58 and line 108

**Comment by nadavsr** [comment]
Confirmed. Thanks for reporting. I'll get it fixed soon and update.

**Comment by thesamet** [comment]
Fixed in 0.4.10
