### ISSUE TITLE
excludeFilter doesn't work

### ISSUE THREAD

**Issue by limansky** [trueaccord/ScalaPB#24]
I'd like to have an ability to exclude some protofiles from code generation. I tried to add:
```
excludeFilter in unmanagedSources := "filename.proto" 
```
to build.sbt, but it is ignored.

**Comment by thesamet** [comment]
The next version of sbt-scalapb (0.6) invokes sbt-protobuf which picks up the proto files. This can be fixed once https://github.com/sbt/sbt-protobuf/pull/29 is merged.

**Comment by limansky** [comment]
Looks like changes in sbt-protobuf are merged now, and new version (0.5.0) is released.
