### ISSUE TITLE
Make serializedSize field @transient

### ISSUE THREAD

**Issue by maspwr** [trueaccord/ScalaPB#25]
ScalaPB makes beautiful case classes, but they include an extra val called `serializedSize`. This field makes it impossible to use a library like [spray-json](https://github.com/spray/spray-json) to automatically generate JSON formatters for these case classes. Marking the `serializedSize` field as `@transient` will resolve this issue.

https://github.com/trueaccord/ScalaPB/blob/425dd2d52a2261c5e63e392243bae8e0c97fe3e8/compiler-plugin/src/main/scala/com/trueaccord/scalapb/compiler/ProtobufGenerator.scala#L400

**Comment by maspwr** [comment]
Awesome! Thanks for updating so fast!

**Comment by thesamet** [comment]
This got released in 0.4.15.

**Comment by maspwr** [comment]
@thesamet Works wonderfully. Thanks!
