### ISSUE TITLE
akka serialization and scalapb

### ISSUE THREAD

**Issue by ahjohannessen** [trueaccord/ScalaPB#27]
Would it make sense to have `com.trueaccord.scalapb.GeneratedMessage` and `com.trueaccord.scalapb.GeneratedEnum` extend `java.io.Serializable`. Reason for asking is that akka serialization picks the wrong serializer due to this:

*In case of ambiguity, i.e. the message implements several of the configured classes, the most specific configured class will be used, i.e. the one of which all other candidates are superclasses. If this condition cannot be met, because e.g. java.io.Serializable and MyOwnSerializable both apply and neither is a subtype of the other, a warning will be issued*

I believe `com.google.protobuf.GeneratedMessage` implements `java.io.Serializable` with `serialVersionUID = 1L`.

**Comment by ahjohannessen** [comment]
thx :+1:

**Comment by thesamet** [comment]
This is in 0.4.15 - let me know how if this helps.

**Comment by ahjohannessen** [comment]
It works great, Akka correctly picks correct serializer, thanks :+1:

**Comment by ZhangBanger** [comment]
Which serializer should akka be picking? I'm having trouble forcing it to pick the protobuf serializer.

**Comment by thesamet** [comment]
You need to implement your own serializer as described in http://doc.akka.io/docs/akka/snapshot/scala/serialization.html

Akka's default proto serializer is for Java generated classes.

**Comment by ZhangBanger** [comment]
Gotcha, thanks!

**Comment by eiennohito** [comment]
You can use my implementation for reference:
https://gist.github.com/eiennohito/5b10d6fb3fd180cfa7fb2a0634b8a3bc

I register it as
```scala
akka {
  actor {
    serializers {
      scalaProto = "ws.eiennohito.utils.serialization.ScalaProtobufSerializer"
    }

    serialization-bindings {
      "com.trueaccord.scalapb.GeneratedMessage" = scalaProto
    }
  }
}
```

**Comment by nattyddubbs** [comment]
The protobuf Akka serializer works I have used it successfully numerous times. It uses reflection to determine whether or not the class adheres to the desired contract (`toByteArray` `fromByteArray`)

`proto = "akka.remote.serialization.ProtobufSerializer"`

**Comment by thesamet** [comment]
@nattyddubbs Nice, I didn't know that! @ZhangBanger can you share a minimal example with the problem you are seeing?

**Comment by ZhangBanger** [comment]
I have this in my config:
```
actor {
    provider = "akka.cluster.ClusterActorRefProvider"
    serializers {
      proto = "akka.remote.serialization.ProtobufSerializer"
    }

    serialization-bindings {
      "com.trueaccord.scalapb.GeneratedMessage" = proto
    }
  }
```

@nattyddubbs @thesamet for some reason, GeneratedMessage does not implement `parseFrom`? Instead it's called from a companion object?

**Comment by ZhangBanger** [comment]
For a little more background, my message type looks something like:

```
message Channel {
    message Message {
    }
}
```

**Comment by thesamet** [comment]
I think I have seen something similar before - Java reflection and nested companion objects. Let me know if this is something you'd like us to fix, by filing another issue.

**Comment by nattyddubbs** [comment]
@ZhangBanger I add an individual entry for each message type that I'll be sending in between Actors in the serialization-binding entry. For example: 
`
actor {
    provider = "akka.cluster.ClusterActorRefProvider"
    serializers {
      proto = "akka.remote.serialization.ProtobufSerializer"
    }

    serialization-bindings {
      "<yourpackagename>.Channel" = proto
      "<yourpackagename>.Message" = proto
    }
  }
`

**Comment by ZhangBanger** [comment]
@nattyddubbs are you able to deal with nested messages? I tried individual entries as well without success

**Comment by nattyddubbs** [comment]
@ZhangBanger I have not used the Akka built in Protobuf serializer for nested messages. Typically nested messages for our use cases would always remain nested and thus not need to be serialized individually.

**Comment by eiennohito** [comment]
@ZhangBanger my solution works for nested messages.

By the way, you can register only the common interface for akka as specified in [its documentation](http://doc.akka.io/docs/akka/snapshot/scala/serialization.html).

**Comment by ZhangBanger** [comment]
@eiennohito  - gotcha, thanks!

@thesamet - let me take another look and see if I can figure out what happened. Would be nice to not have to write more code / add more deps.

**Comment by nattyddubbs** [comment]
@eiennohito That's really good to know. Maybe we'll look at using that approach in the future 👍
