### ISSUE TITLE
import does not work correctly

### ISSUE THREAD

**Issue by Mask051** [trueaccord/ScalaPB#32]
#org/a/a.proto
syntax = "proto2";
package org.a;

message Msg {
    extensions 16 to max;
}

#org/b/b.proto
syntax = "proto2";
package org.b;
import "org/a/a.proto";

extend Msg {
    optional Test test = 16;
}

message Test {}

These configuration throws error while compiling:

protoc-jar: executing: [C:\Users\D\AppData\Local\Temp\protoc3931572059064664031.exe, --plugin=protoc-gen-scala=C:\Users\D\AppData\Local\Temp\scalapbgen2982993506159287014.b
at, -ID:\my_app\app, -ID:\my_app\target\protobuf_external, --scala_out=:D:\my_app\target\scala-2.11\src_managed\main
\compiled_protobuf, D:\my_app\app\org\a\a.proto,
 D:\my_app\app\org\b\b.proto]
org/b/b.proto:6:8: "Msg" is not defined.
[libprotobuf WARNING google/protobuf/descriptor.cc:6117] Warning: Unused import: "org/b/b.proto" imports "org/a/a.proto" which is not used.
java.lang.RuntimeException: protoc returned exit code: 1

**Comment by thesamet** [comment]
On a fast first read, it seems like the error is generated by protoc, not ScalaPB. In b.proto, the package name is missing. Can you try:

```
extend org.a.Msg {
optional Test test = 16;
}
```

This should compile now. This should pass protoc, but ScalaPB currently does not support extensions.

**Comment by Mask051** [comment]
It works. Thanks
