### ISSUE TITLE
0.5.9 has sbt generated classes in the packaged scalapb-runtime jar

### ISSUE THREAD

**Issue by iphydf** [trueaccord/ScalaPB#35]
I don't know whether this has been fixed. I didn't see a bug in the closed bugs list about this, so just to make sure it doesn't happen again, here is a ticket. Files of the form `project/target/config-classes/$<hex number>$.class` (e.g. `project/target/config-classes/$a25026b6814a5648333d$.class`) can be found in 0.5.9 jars from maven. These confuse several tools and make ScalaPB unusable on Android.

**Comment by iphydf** [comment]
FYI: if I build this from source (master branch), the resulting jars correctly do not contain the config-classes.

**Comment by thesamet** [comment]
Must be some sbt plugin I locally have that causes this.

**Comment by zbsz** [comment]
It's the same for 0.4.15, your published jar includes lots of unnecessary files and directories

**Comment by thesamet** [comment]
This is fixed in 0.5.13 and 0.4.18. Thanks for reporting!
