### ISSUE TITLE
Why are option fields with default value converted to Option[..] ?

### ISSUE THREAD

**Issue by pm47** [trueaccord/ScalaPB#36]
Hi,

First, thanks for the great work !

I'm wondering why this :
`message my_message {
  optional uint32 foo = 1 [ default = 0 ];
}`

results in foo being an Option[Int], not an Int. It will always have a value right ?

Cheers

**Comment by thesamet** [comment]
Using an option makes it possible for your code to detect the distinction of whether the field actually appears in the binary representation of a message or is absent. Without it, it will be impossible for your code to tell whether the default value has been set explicitly, or was just missing. This is consistent with the Java implementation (hazzers are generated too).

It would also not be nice to change the type of a generated field if a default value is provided.

To bypass the option, just use `getFoo` whenever you need the value.

**Comment by pm47** [comment]
That makes sense. Thanks !
