### ISSUE TITLE
Output directory conflicts with IntelliJ

### ISSUE THREAD

**Issue by jportway** [trueaccord/ScalaPB#37]
When IntelliJ imports an SBT project using the ScalaPB plugin it adds both directories:
*"src_managed / main"* and *"src_managed / main / compiled_protobuf"* to it's internal build system. 
So when you build the project with IntelliJ the generated classes get included twice, causing conflicts.

is it possible to build directly into the "src_managed / main" directory ?
sbt-protobuf has some [instructions](https://github.com/sbt/sbt-protobuf#changing-the-location-of-the-generated-java-files) about this, but it's not obvious how they map to ScalaPB.

**Comment by nadavsr** [comment]
Can you try setting "scalaSource in PB.protobufConfig", that should do it.

**Comment by jportway** [comment]
That worked. Brilliant! Thank you.
Perhaps this is obvious to those who are experienced with SBT but for newcomers like me it would be really useful to have it documented. I've been striuggling all day with verious approaches to the problem.
thanks again.

**Comment by dmolesUC3** [comment]
@jportway would you mind posting exactly what you did to which build files? I tried adding

```scala
scalaSource in PB.protobufConfig <<= (sourceManaged / "main")
```

to my `build.sbt` and refreshing the project, but `target/src_managed/main` isn't showing up as a source folder in the IDEA module.

(It doesn't help that I'm new to SBT, having built all my Scala projects with Gradle till now.)

**Comment by angelcervera** [comment]
https://github.com/trueaccord/ScalaPB/issues/120

**Comment by angelcervera** [comment]
In my case, the problem was the protobuff Idea plugin:

1. Remove the idea protbuff plugin.
2. Close Idea
3. Remove folders related with idea (.idea and .idea_modules)
4. Import the project.

**Comment by dholbrook** [comment]
This is how I configured it to work with InteliJ

```
PB.protobufSettings
scalaSource in PB.protobufConfig <<= (sourceManaged in Compile)
```

**Comment by angelcervera** [comment]
@dholbrook #126

**Comment by dantodor** [comment]
I tried the same, but for whatever reason in IntelliJ protobufConfig shows in red, as if it's not a member of PB ... any idea(pun not intended) why ?
Thanks!

**Comment by thesamet** [comment]
Are you using `sbt-protoc`? With it the defaults should just work with IntelliJ.

**Comment by dantodor** [comment]
In plugins.sbt I have

addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.1")

libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.5.42"

In build.sbt I have
PB.targets in Compile := Seq(scalapb.gen() -> (sourceManaged in Compile).value)

When I try to add the advised line in build.sbt, the .protobufConfig is red, assume somehow IntelliJ doesn't sees it as a member of PB ... what am I doing wrong ?

**Comment by thesamet** [comment]
In `sbt-protoc` there's no `PB.protobufConfig`. What are you trying to accomplish?

**Comment by dantodor** [comment]
I'm trying to get visibility of the generated classes in the project. As it is right now, all classes are shown in red, as they're not defined. Compiling via sbt works. But it's a nuisance to not be able to see class members in IntelliJ

**Comment by thesamet** [comment]
Try importing the project to IntelliJ now that you have a few proto files. It looks like if there are no protocol buffers at the time the IntelliJ project is created it will not find the generated sources.

**Comment by dantodor** [comment]
I'll try that, thank you

**Comment by ndeverge** [comment]
For those still having the issue, I made it work with

`scalaSource in sbtprotoc.ProtocPlugin.ProtobufConfig := (Compile / sourceManaged).value`
