### ISSUE TITLE
Value classes for primitive single-element message?

### ISSUE THREAD

**Issue by seacourtaw** [trueaccord/ScalaPB#4]
Would it be possible for messages with one required field of value type to extend AnyVal? I am presuming not, but it's not completely clear from a cursory scan of the code.

**Comment by nadavsr** [comment]
I looked into this and the change isn't as straightforward as I hoped. Given that required fields are going to be dropped in the upcoming proto3 syntax, there is a little value in implementing this. I'm interested to know if the AnyVal optimisation makes a measurable performance difference in your use case and then we can figure out if it's worth the investment.
 
In the mean time, I suggest that you use your own case classes that extend AnyVal during the life of your program, and map them to/from protobufs when you need to serialize/deserialize.
