### ISSUE TITLE
use printToUnicodeString instead of printToString in generated toString

### ISSUE THREAD

**Issue by eiennohito** [trueaccord/ScalaPB#41]
Because otherwise debugging of non-english applications become a nightmare and world is not just English.

An option in the build would be a solution as well.

**Comment by eiennohito** [comment]
patch for simple replace
https://github.com/eiennohito/ScalaPB/tree/forced-version

**Comment by thesamet** [comment]
Can you send a pull request?

On Thu, Sep 10, 2015 at 1:18 AM, Arseny Tolmachev <notifications@github.com>
wrote:

> patch for simple replace
> https://github.com/eiennohito/ScalaPB/tree/forced-version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/41#issuecomment-139163988>.
>



-- 
-Nadav

**Comment by eiennohito** [comment]
#42 closes this
