### ISSUE TITLE
Maps in proto2 files

### ISSUE THREAD

**Issue by eiennohito** [trueaccord/ScalaPB#43]
It seems to be possible according to the docs (https://developers.google.com/protocol-buffers/docs/proto?hl=en#oneof), however codegen generated invalid messages.

for simple message like

    syntax = "proto2";

    message MapTest {
      map<string, int32> map1 = 1;
      map<string, float> map2 = 2;
    }

it generates map entries like case class `(key: Option[String], value: Option[Int])`, but the type of map is `Map[String, Int]`. I believe that options are not needed here.

**Comment by thesamet** [comment]
If you switch to syntax="proto3" it will work as you expect. For syntax="proto2" it needs to be this way for backward compatibility.

**Comment by eiennohito** [comment]
For proto3 I believe that #40 still holds and there should be a mean for not wrapping fields in options.
