### ISSUE TITLE
Is there any plan to support GRPC?

### ISSUE THREAD

**Issue by xuwei-k** [trueaccord/ScalaPB#44]
http://www.grpc.io/

**Comment by zackangelo** [comment]
:+1:

I've modified the Java GRPC compiler to create Scala service stubs instead. I'd be interested in porting that work over if it's something others are interested in. 

We'd also need proto3 support. I think we're close, there doesn't seem to be a big difference between the two. The biggest change needed I've found is for all fields to be optional.

**Comment by hepin1989** [comment]
@zackangelo 
currently the grpc don't support scala directly,seems like we could leverage work here just as what you said.
it's beta now,I think will be soon to the GA stage.

**Comment by tayama0324** [comment]
I am woking on scala gRPC support with @xuwei-k. We will fork ScalaPB rather than sending pull requests to get things done quickly. Let us know if you have any concerns. This issue will be closed in a few days.

**Comment by thesamet** [comment]
@tayama0324 nice, would definitely love to have it merged here when you're ready.

**Comment by iphydf** [comment]
About making all fields optional: can this be a setting, so I can choose to make all fields non-optional, instead? Wrapping everything in an Option can become too much overhead. The proto3 semantics allow for this (see [this example](https://github.com/google/protobuf/blob/master/examples/ListPeople.java#L15)).

**Comment by thesamet** [comment]
@iphydf the above comment seem to be unrelated to this bug - can you please file a different issue? FWIW, in Scalapb >= 0.5, primitives are not wrapped in an Option for proto3.

**Comment by agnek** [comment]
@xuwei-k @tayama0324 can I help you and contribute some code? I want to use grpc with at work.

**Comment by thesamet** [comment]
Status update: merge @xuwei-k PR into the grpc branch here. Added an implementation of a Marshaller to avoid conversions to/from Java protobufs.

**Comment by xuwei-k** [comment]
> Added an implementation of a Marshaller to avoid conversions to/from Java protobufs.

Excellent! thanks a lot :smile:

**Comment by thesamet** [comment]
The work has been merged into master and released in 0.5.18. Thanks @xuwei-k for doing the heavy lifting!

**Comment by xuwei-k** [comment]
FYI, I and @tayama0324 translated grpc-java examples. https://github.com/xuwei-k/grpc-scala-sample

**Comment by thesamet** [comment]
This is really awesome - thank you! When I get to write the docs for
ScalaPB/grpc I'll make sure to link to this repo.

On Fri, Dec 18, 2015 at 8:04 PM, kenji yoshida <notifications@github.com>
wrote:

> FYI, I and @tayama0324 <https://github.com/tayama0324> translated
> grpc-java examples. https://github.com/xuwei-k/grpc-scala-sample
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/44#issuecomment-165944682>.
>



-- 
-Nadav

**Comment by abhinavzspace** [comment]
This is great. Can you show us a few hints on where to look for the code for implementing grpc on our projects @xuwei-k and @tayama0324 in [https://github.com/xuwei-k/grpc-scala-sample](https://github.com/xuwei-k/grpc-scala-sample). Thanks a lot for this excellent work.

**Comment by mkotsbak** [comment]
Documentation: https://scalapb.github.io/grpc.html
