### ISSUE TITLE
Add an option to wrap primitives to Option[]

### ISSUE THREAD

**Issue by prettynatty** [trueaccord/ScalaPB#54]
In some cases zeros does not make sence. For example, I have a model Event, stored in relational database:
```
message Event {
  bytes data = 1;
  int64 deleted_at = 5 [(scalapb.field).type = "org.joda.time.DateTime"];
}
```
In the past Event did not have a deleted_at, but it had a boolean is_deleted. When deleted_at appeared, it had been set to the epoch start for every deleted event and to NULL for the rest. So, if deleted_at is not an Option, there is no way to determine if event was deleted.

**Comment by thesamet** [comment]
Two options: 

Option A:

```
int64 deleted_at = 5 [(scalapb.field).type = "Option[org.joda.time.DateTime]"];
```

and define a `TypeMapper[Int, Option[org.joda.time.DateTime]]` that maps `0` to `None`.

Alternatively, you can define:
```
message NullableTime {
  int64 deleta_at = 1
}
```

Message fields are always in options, and you can then use a custom type for it.

**Comment by prettynatty** [comment]
I like NullableTime idea, thanks. It totally covers my case.

**Comment by zackangelo** [comment]
What's the reasoning behind not using `Option` for optional types in messages? Is it something related to how protobuf messages are encoded (e.g., they can't convey absent values)?

**Comment by thesamet** [comment]
Exactly. The receiving end has no way of telling if an int32 field was assigned to zero or whether it was unassigned. See note here: https://developers.google.com/protocol-buffers/docs/proto3?hl=en#default

**Comment by zackangelo** [comment]
@thesamet this seems like a pretty big regression compared to proto2, am I missing something? :)

**Comment by zackangelo** [comment]
@thesamet it looks like proto3 betas will include built-in nullable primitives: https://github.com/google/protobuf/issues/159#issuecomment-76240356. 

Could we map these to `Option` types in the generated code? 

That being said, I can't find any trace of them in the repo yet.

**Comment by zackangelo** [comment]
Found them: https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by zackangelo** [comment]
Trying to use these built-in wrapped types results in compile-time errors: 

```[error] /Users/zack.angelo/git/galaxy/interfaces/target/scala-2.11/src_managed/main/compiled_protobuf/com/bigcommerce/services/catalog/Product.scala:37: value serializedSize is not a member of com.google.protobuf.Int32Value
[error]       if (id.isDefined) { __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(id.get.serializedSize) + id.get.serializedSize }```

Any idea how to fix?
