### ISSUE TITLE
Plugin architecture for custom code generation

### ISSUE THREAD

**Issue by PerWiklander** [trueaccord/ScalaPB#61]
Since I have all my messages as .proto I would like to take advantage of that and generate all boiler plate code for my application.

Examples of generated code other than plain case classes:

* Custom JSON ser / dser
* Slick table models
* Web forms with input validation

What I'm looking for here is an easy way of plugging my own custom code generator into ScalaPB's pipeline.

Any thoughts on that? How hard is it to do this today if I fork the project?

**Comment by thesamet** [comment]
Hi Per,

The place to start with is at:
https://github.com/trueaccord/ScalaPB/blob/master/compiler-plugin/src/main/scala/com/trueaccord/scalapb/compiler/Process.scala

In `runWithInputStream` the request from protoc (in form of a
CodeGeneratorRequest) is parsed and passed to ProtobufGenerator.

protoc supports invoking multiple plugins in a single run. In Process.scala
there is a trick that we do to make protoc send the CodeGeneratorRequest
back to the JVM that invoked it (which is done differently for Windows and
Linux/Mac), but it would be fairly straightforward to extend the trick to
handle multiple plugins...

On Mon, Dec 7, 2015 at 4:34 PM, Per Wiklander <notifications@github.com>
wrote:

> Since I have all my messages as photo I would like to take advantage of
> that and generate all boiler plate code for my application.
>
> Examples of generated code other than plain case classes:
>
>    - Custom JSON ser / dser
>    - Slick table models
>    - Web forms with input validation
>
> What I'm looking for here is an easy way of pluggin my own custom code
> generator into ScalaPB's pipeline.
>
> Any thoughts on that? How hard is it to do this today if I fork the
> project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/61>.
>



-- 
-Nadav

**Comment by thesamet** [comment]
ScalaPB uses a new SBT plugin sbt-protoc, which allows creating custom generators. 

See https://github.com/thesamet/sbt-protoc
