### ISSUE TITLE
Add support to convert messages to Json

### ISSUE THREAD

**Issue by sridharpg** [trueaccord/ScalaPB#62]
Currently there is no built-in serializer to convert messages ↔ Json. This could come in handy to send a readable Json to the client.

**Comment by nykolaslima** [comment]
@thesamet do you guys have any plan on implementing it?

**Comment by thesamet** [comment]
No concrete plans, PR welcome. What JSON library should we be using for Scala? There are so many.

**Comment by thesamet** [comment]
Done! http://trueaccord.github.io/ScalaPB/json.html
