### ISSUE TITLE
GeneratedMessageCompanion#parseFrom always successful even for incompatible types

### ISSUE THREAD

**Issue by mushtaq** [trueaccord/ScalaPB#66]
`println(B.parseFrom(A("hello", 100).toByteArray)) // B(0, "")`
`println(A.parseFrom(B(100, "hello").toByteArray)) // A("", 0)`

Is this intended? Then why do we have a "validate" method? Is there a sbt setting to change these defaults and make it throw exception?

**Comment by thesamet** [comment]
It depends on the definitions of A and B, but generally there is no way for the parser to know that it is getting bytes that are meant for a different message types. In some cases, it can detect that a message does not make sense and then it would throw an exception. The validate function is returning a `Try` that fails when those cases happen.
 
This behavior is a feature in the protobuf wire format that allows you to evolve your message schema. 
https://developers.google.com/protocol-buffers/docs/proto#updating
