### ISSUE TITLE
Support for sealed traits

### ISSUE THREAD

**Issue by PerWiklander** [trueaccord/ScalaPB#67]
*Use case*: Exhaustive pattern matching of related domain events.

A file level option like:
```option (scalapb.message).sealedTrait = "DomainEvent";```

This would cause all messages in the ```.proto``` file to be put in the same ```.scala``` file along with a
```sealed trait DomainEvent {}```

**Comment by thesamet** [comment]
I wonder if it makes sense to automatically have all the messages in the file extend the sealed trait, or individual messages should be opted in via `option (scalapb.message).extends`

**Comment by PerWiklander** [comment]
Consider that it is a sealed trait and all extending messages have to be generated in the same ```.scala``` file. It would be confusing if only some of the messages from a ```.proto``` end up in the same file and others in separate files.

At least in my use case it would require copy+pasting ```option (scalapb.message).extends``` into every message of the file.

**Comment by ngthanhtrung** [comment]
Do you have any plan to implement this?

**Comment by thesamet** [comment]
See example usage in : https://github.com/trueaccord/ScalaPB/blob/master/e2e/src/main/protobuf/sealed_trait.proto

**Comment by PerWiklander** [comment]
In your example the sealed trait in the preamble has methods prefixed with `get`,  `getFoo` and  `getBar`. Is that required? And does it even work with the generated case class, which I assume would have public vals named  `foo` and `bar`?

**Comment by PerWiklander** [comment]
Or was that just an example? I guess my initial example for this issue doesn't require any defs on the sealed trait, since it's just a grouping trait for pattern matching.

**Comment by thesamet** [comment]
It's just an example. You can leave the sealed trait empty. There's no
requirement to define anything in it.

**Comment by ngbinh** [comment]
thanks! This is great!
