### ISSUE TITLE
Unnecessary long filename for InternalFields_xxx files

### ISSUE THREAD

**Issue by andresch** [trueaccord/ScalaPB#73]
I did run (on windows) into the issue of too long file names which caused the compiler to fail writing the InternalFields_xxx.scala document. 

While it is primarily Windows to blame for the last century 256 path length limitation, scalaPB seems to generate filenames that are unnecessarily long: xxx contains the full path (from the protobuf root), but since the files are stored in the scala-package directory, using the .proto-filename alone should be sufficient. In my case this would have prevented the error from happening as my protobuf files reside in a quite deep file-hierarchy.

I could workaround the problem by changing my package-structure (shorter names), so no show stopper.

More important than this fix would be a good error message that indicates what went wrong. It took me quite some time to figure out what's going on.

Nevertheless: Thanks a lot for providing and supporting scalaPB!

**Comment by thesamet** [comment]
Could you try to your sbt config

   scalacOptions ++= Seq("-Xmax-classfile-name", "100")

or some small enough number?

**Comment by thesamet** [comment]
What's the exact error you are getting? Agree that the full path isn't necessary and it could easily be fixed.

**Comment by andresch** [comment]
the error message I received is just

    {scala-package-path}/InternalFields_{packedProtoFilePath}.scala: No such file or directory

**Comment by andresch** [comment]
I tested the suggested scalacOption but it didn't have any impact -- would have been a surprise to me, as the error happens in scalaPB (or eventually in protoc), not in the scala compiler

**Comment by thesamet** [comment]
Got it, you're right. We had in the past a similar issue that caused the generated class files to be too long when the protos are nested.

I pushed a fix and 0.4.21 will appear shortly.
