### ISSUE TITLE
broken sbt build due to sbt-protobuf dependency

### ISSUE THREAD

**Issue by forestofrain** [trueaccord/ScalaPB#74]
I am unable to add this plugin `addSbtPlugin("com.trueaccord.scalapb" % "sbt-scalapb" % "0.4.20")` to my build due to issue in sbt-protobuf: see sbt/sbt-protobuf#37 for details.

```
error: reference to compile is ambiguous;
it is imported twice in the same scope by
import _root_.sbtprotobuf.ProtobufPlugin._
and import Keys._
  settings(mainClass in compile := Some("whatever")
```

**Comment by thesamet** [comment]
When you true sbt-ascalapb, you don't need sbt-protobuf (it invoked it for you).

Would it be possible for you to avoid importing the plugin into the main scope. See:

See http://trueaccord.github.io/ScalaPB/sbt-settings.html

**Comment by forestofrain** [comment]
Sorry for my confusion with the details. The issue details from `sbt-protobuf` were me including that plugin to show the author that the issue is with his plugin. When I include your plugin only, I still get a broken build because your plugin depends on `sbt-protobuf`. I wanted you to be aware that this dependency is causing an issue, not your plugin code.

You mention that I don't need `sbt-protobuf`, but I didn't see anything in the linked documentation that implies otherwise. Do you have details? Do you have an example of how to "avoid importing the plugin into the main scope"?

I am able to include your plugin if I use the workaround of aliasing `compile` using
```
import Keys.{compile => sbtCompile}
```
Once again, the real issue is with `sbt-protobuf` and me needing to use `settings(mainClass in compile := Some("whatever")`

**Comment by thesamet** [comment]
If you'd like sbt-scalapb to generate Java classes enable javaConversions: import sbtprotobuf.{ProtobufPlugin=>PB}

The problem you are seeing with sbt-protobuf come from the fact that you are importing both sbtprotobuf.ProtobufPlugin._ and Keys._ and there is a name conflict on `compile`. This can happen between any pair of import, so I don't it's necessarily a bug. If you look at https://github.com/sbt/sbt-protobuf/blob/master/README.md the suggested import is: 

```
import sbtprotobuf.{ProtobufPlugin=>PB}
```

**Comment by thesamet** [comment]
Also wanted to add that we are moving away from sbt-protobuf since it's unmaintained.
