### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by andresch** [trueaccord/ScalaPB#75]
While I can successfully use scalaPB on my local machine (with jdk8 installed), our CI system only hosts for scala 10.x jdk7. Now I run into class format conflicts:

    java.lang.UnsupportedClassVersionError: com/trueaccord/scalapb/Scalapb : Unsupported major.minor version 52.0

AFAIK jdk 8 will only be officially supported with scala 2.12 it would be great if the published 2.10/2.11 artifacts of scalaPB would still use older class formats.

If that's not easily possible, any suggestion for a workaround?

**Comment by thesamet** [comment]
Fixed in 0.4.21

**Comment by worldwar2008** [comment]
I meet the same problem with "scala-2.10.4","jdk-8","protoc-2.6.1"
