### ISSUE TITLE
Getting 'protoc not found' error

### ISSUE THREAD

**Issue by vvviiimmm** [trueaccord/ScalaPB#83]
Hello,

Trying to use the plugin but getting this error message saying protoc couldn't be found.

> \[error\] (protobuf:protobufGenerate) error occured while compiling protobuf files: Cannot run program "protoc": error=2, No such file or directory

I do have protoc installed in my path:

> ➜  ~  which protoc
> /usr/local/bin/protoc
>➜  ~  protoc --version
>libprotoc 2.6.1

Not sure if thats an issue, but I did everything from installation guide. Any help would be greatly appreciated.

**Comment by thesamet** [comment]
Sounds like a PATH issue, try setting the path to protoc explicitly in SBT:
`
PB.protoc in PB.protobufConfig := "/usr/local/bin/protoc"
`

Alternatively, you can use protoc-jar as explained in "Running without Protoc" at https://trueaccord.github.io/ScalaPB/sbt-settings.html

**Comment by vvviiimmm** [comment]
Thanks a lot, setting the path explicitly helped.

**Comment by samuelpraveen** [comment]
Hi,

Obserning the below error even after installing protobuf 3.1.0
root@ubuntu:/usr/local/bin# protoc --version
-bash: /usr/bin/protoc: No such file or directory

Could you please help?

**Comment by thesamet** [comment]
Hi @samuelpraveen ,

1. It looks like you have problem installing protoc, so it makes sense to ask it at the protobuf mailing list, not ScalaPB. However, if you just did `make install` and using bash try running `rehash` and `sudo ldconfig` if needed. 

2. If you are using ScalaPB through sbt-protoc, you don't have to install protoc. Out of the box `protoc` is provided to you as a dependency.
