### ISSUE TITLE
Compilation not working.

### ISSUE THREAD

**Issue by abhinavzspace** [trueaccord/ScalaPB#84]
I am totally new to protobuf's. We are using Play Framework with Java. I have implemented everything specified in the docs.
Following are my settings in build.sbt:

```
PB.protobufSettings

PB.javaConversions in PB.protobufConfig := true

PB.runProtoc in PB.protobufConfig := { args =>
  com.github.os72.protocjar.Protoc.runProtoc("-v300" +: args.toArray)
}
```

Also added these two libraryDependencies inside build.sbt:

```
"io.grpc" % "grpc-all" % "0.9.0",
"com.trueaccord.scalapb" %% "scalapb-runtime-grpc" % "0.5.21"
```

And my plugins.sbt contains following lines:

```
addSbtPlugin("com.trueaccord.scalapb" % "sbt-scalapb" % "0.5.21")

libraryDependencies += "com.github.os72" % "protoc-jar" % "3.0.0-b2"
```

I am not getting any errors on running "activator clean compile". But it is also not running compilation of the .proto file in src/main/protobuf. Though a folder named "compiled_protobuf" is getting created at target/scala-2.11/src_managed/main/.

I don't understand what I am missing. I ultimately want to use gRPC.

**Comment by thesamet** [comment]
Can you try "sbt clean compile"? I have never tried using ScalaPB with activator. If it doesn't work, can you share a github project that has this problem?

**Comment by abhinavzspace** [comment]
I checked on the net, activator runs sbt internally. Its same. But I will try sbt also.

Meanwhile can you please have a look at [build.sbt and plugins.sbt](https://gist.github.com/abhinavzspace/6296a14c7b9aa09e32e3)

**Comment by abhinavzspace** [comment]
[This link](http://stackoverflow.com/questions/25084045/where-is-sbt-inside-typesafe-activator) tells that activator is just a little fancy wrapper around sbt and there is no way to invoke sbt directly. I am still looking into any possible way to run sbt directly.

**Comment by thesamet** [comment]
Maybe try `activator shell` and inside it `clean` and `compile`. For running sbt directly, just install SBT and run it from the project's home directory, nothing else is normally needed.

**Comment by abhinavzspace** [comment]
Tried `activator shell` and through SBT also now. No luck.

**Comment by abhinavzspace** [comment]
Are my `.sbt` files fine?

**Comment by abhinavzspace** [comment]
Was trying different things. Commenting the following line resulted in successful compilation:

`lazy val root = (project in file(".")).enablePlugins(PlayJava)`

But this is somehow very important. Any way to work around this?

**Comment by thesamet** [comment]
maybe just 

enablePlugins(PlayJava)

**Comment by thesamet** [comment]
Another alternative is to switch to a multi-project build:

```
  lazy val protos = project
    .settings(
      PB.protobufSettings ++ Seq(
        // protoc in PB.protobufConfig := "/path/to/protoc", 
        // Optionally read protos from parent directory, otherwise it's protos/src/main/protobuf
        // sourceDirectory in PB.protobufConfig := file("../some/path/to/proto")
     ))
```

The protobufs should go in "protos/src/main/protobuf" (you can customize, see comments above)

Then make the root project depend on it:
```
lazy val root = (project in file(".")).enablePlugins(PlayJava).dependsOn(protosProject)
```

**Comment by abhinavzspace** [comment]
I am trying this. Not working yet. But I will figure it out.

I will let you know. Thanks a lot.

**Comment by abhinavzspace** [comment]
Is it anyway possible to do this without updating sbt version. I am getting evicted warning.

From last 6 hours I am struggling with this problem only. :(

**Comment by abhinavzspace** [comment]
Finally, its working now. I ended up creating separate build.sbt file for protos folder inside root. Sbt is beyond my understanding. Thanks for the help.
