### ISSUE TITLE
Option to change repeated fields collection type from Seq to IndexedSeq

### ISSUE THREAD

**Issue by andresch** [trueaccord/ScalaPB#97]
Is there a way to change the generated collection type from Seq to some other collection type (e.g. IndexedSeq)?

The way I interpret the option scalapb.field.type this allows to set another class for the object type, but not for the collection type.

**Comment by thesamet** [comment]
@andresch , not now, but it's an easy fix to change the signature. Though, regardless, when you are parsing a message from bytes, ScalaPB actually assigns a Vector (which is an IndexedSeq), so you do get an IndexedSeq at runtime.

**Comment by eiennohito** [comment]
An option for primitive types to use arrays instead of vectors would be great as well.

**Comment by andresch** [comment]
@thesamet sorry for the late reply. The fact that ScalaPB assigns internally a Vector was sufficient knowledge in our case. So no priority from my side. Thanks!
